---
title: "Generalized Cross Validation"
author: "Shakkya Ranasinghe"
date: "2023-09-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(rlang)
require(here)

GInv <- MASS::ginv
f <- glue::glue

i_am("Code/gcv.Rmd")
source(here("Code/utils.R"))
```


# Specify model

```{r model}
n = 100
functionName = "DGP1"

modelvals = modelSp(functionName, n =n)
xargs = modelvals$xargs
x = modelvals$x
fx = modelvals$fx

for (i in 1:modelvals$xargs) {
  assign(f("x{i}"), x[i, ]  %>% unlist())
}


tibble(x1, fx) |> 
    ggplot() + 
    geom_point(aes(x=x1, y=fx), color = "Steelblue4") + 
    labs(title = "Starting data: x & fx") + 
    theme_classic()
```


```{r kernel}
kernel <- bernoulliKernel

logLambda <- seq(-10, 10, length = 50)
listLambda <- exp(logLambda)
```


# Compute fitted value for each lambda iteratively. 

```{r}
fitValues <- function(x, fx, lambda, kernel) {
  I = diag(1, nrow = length(fx))
  xDim = min(dim(x))
  Rkernel = c()
  
  for (i in 1:xDim) { # assign each row to x1, x2 ...>
      assign(f("xN{i}"), x[i, ] %>% unlist())
  }
  listName = "RKL"
  for (j in 1:xDim) {
      xNj = base::eval(base::parse(text = f("xN{j}")))
      # log_info(f("Calculating outer Rkernerl for <x{j}, x{j}>"))
      # assign(f("Rkernel{j}"), outer(xj, xj, bernoulliKernel))
      # print(f("Rkernel{j}"))
      # Rkernel[f("Rkernel{j}")] = evalHere(f("Rkernel{j}")) %>% list() ## problem
      Rkernel[[f("{listName}{j}")]] = outer(xNj, xNj, bernoulliKernel)
  }
  
  R = mprod(kernel = Rkernel, xdim = xDim, name = listName, I = I)
  
  
  coef <- (R + n*lambda*I) |> GInv()
  coef <- coef %*% matrix(fx)
  
  phi <- R
  fHat <- (t(phi) %*% coef) |> c()
  S = t(phi)%*%((R+n*lambda*I) |> GInv())
  return(list(fHat, S))
}

df = tibble(y=fx)
sf = tibble(lambda = purrr::map_chr(listLambda, f))

for (i in 1:length(listLambda)) {
  lambda = listLambda[i]
  # assign("name", f("{round(lambda, 5)}"))
  # f("Calculating fitted value for lambda: {lambda}") |> print()
  # varName = f("fHat_{i}")
  valuesReturn = fitValues(x, fx, lambda, kernel)
  valuesReturn[1][[1]] -> vals
  valuesReturn[2][[1]] -> s
  df[, i+1] <- vals
  sf[i, 2] <- nest(as.data.frame(s))
}

colnames(df) <- c("x", purrr::map2_chr("fHat", seq(1:50), .f = f))
df |> 
  head()

sf |> 
  head()
```
Calculate cross validation value [GCV](https://stats.stackexchange.com/questions/77527/the-cross-validation-cv-and-the-generalized-cross-validation-gcv-statistics)

```{r gcv}
gcv = vector()
df |> 
  mutate(
    across(fHat1:fHat50, ~ sum((fx-.x)^2)
           )
         ) |> 
  select(-x) |> 
  slice(1) |> 
  unlist() -> fitGCV

# calcualte generalized cross validation value 
for (i in 1:nrow(sf)) {
  gcv[i] <- {
    fitGCV[i] / { 1- (
    sum(diag( # trace
      sf[i, 2] |> unnest(cols=c(data)) |> as.matrix() # = S
    )) / (n)
    )}^2
  } / (n)
}

tibble(gcv, logLambda) %>% 
  ggplot(aes(y = gcv, x = logLambda)) +
  geom_point()

gcv |> as_tibble_col(column_name = "gcv") |> 
  bind_cols(as_tibble_col(listLambda, column_name = "lambdaValue")) |> 
  arrange(gcv) |> 
  head(5) -> minGCV

minGCV |> 
  mutate(lambdaValue = as.character(lambdaValue)) |> # we wanna display lambda values as category in plot
  mutate(count = c(rep(10, 5))) |>  # these two steps replicate each row by count many times
  uncount(count)  |>  
  reshape2::melt(id = "lambdaValue") |> 
  bind_cols(as_tibble_col(rep(seq(1:10), 5), column_name = "index")) |> # value is GCV value
  ggplot() + 
  geom_line(aes(x=index, y = value, col=lambdaValue), lwd = 2) + 
  labs(color = "Lambda Value", y = "GCV")

```

```{r}
minlambdaGCV <- minGCV[{which.min(minGCV$gcv)}, 2] |> pull()

f("Best Fit is given with lambda value: {minlambdaGCV}") |> 
  print()

f("Best Fit is given with lambda value: {round(minlambdaGCV, 4)}") |> 
  print()

minGCV  |>
  arrange(gcv)
```

```{r}
minFitFHat <- fitValues(x=x, y=fx, kernel=kernel, lambda=minlambdaGCV)

dfOri <- tibble(x, fx)
dfMinFit <- tibble(x, lambdaWithMinGCV=minFitFHat[[1]])
dfOri %>% 
  left_join(dfMinFit, by='x') %>%  # get the corresponding fitted value to x
  reshape2::melt(id='x') %>% # flatten the table so that we can plot as one variable but two groups
  ggplot() + 
  geom_point(aes(x=x, y=value, col=variable))
```


```{r}
print("do this")
```












